import { cp, mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const source = path.join(root, 'src');
const output = path.join(root, 'dist');

async function copy(sourcePath, destinationPath) {
  await mkdir(path.dirname(destinationPath), { recursive: true });
  await cp(sourcePath, destinationPath, { recursive: true });
}

await rm(output, { recursive: true, force: true });
await mkdir(output, { recursive: true });

const contentDirectory = path.join(source, 'content');
const contentFiles = (await readdir(contentDirectory))
  .filter(file => file.endsWith('.js'))
  .sort((left, right) => left.localeCompare(right));
const contentParts = await Promise.all(
  contentFiles.map(file => readFile(path.join(contentDirectory, file), 'utf8'))
);
const contentBundle = [
  '// Generated by scripts/build.mjs from src/content/*.js. Do not edit directly.',
  ...contentParts.map(part => part.trimEnd()),
  ''
].join('\n\n');
await writeFile(path.join(output, 'content.js'), contentBundle, 'utf8');

const backgroundDirectory = path.join(source, 'background');
const backgroundFiles = (await readdir(backgroundDirectory))
  .filter(file => file.endsWith('.js'))
  .sort((left, right) => left.localeCompare(right));
const backgroundParts = await Promise.all(
  backgroundFiles.map(file => readFile(path.join(backgroundDirectory, file), 'utf8'))
);
const backgroundBundle = [
  '// Generated by scripts/build.mjs from src/background/*.js. Do not edit directly.',
  ...backgroundParts.map(part => part.trimEnd())
].join('\n\n') + '\n';
await writeFile(path.join(output, 'background.js'), backgroundBundle, 'utf8');

const countryBundle = [
  '// Generated by scripts/build.mjs from countryData.generated.js and countryFlags.js. Do not edit directly.',
  (await readFile(path.join(source, 'shared', 'countryData.generated.js'), 'utf8')).trimEnd(),
  (await readFile(path.join(source, 'shared', 'countryFlags.js'), 'utf8')).trimEnd(),
  (await readFile(path.join(source, 'shared', 'originRules.js'), 'utf8')).trimEnd()
].join('\n\n') + '\n';
await writeFile(path.join(output, 'countryFlags.js'), countryBundle, 'utf8');

const rootFiles = [
  ['manifest.json', 'manifest.json'],
  ['pageScript.js', 'pageScript.js'],
  ['shared/backup.js', 'backup.js'],
  ['shared/webext.js', 'webext.js']
];
for (const [from, to] of rootFiles) {
  await copy(path.join(source, from), path.join(output, to));
}

for (const page of ['popup', 'dashboard', 'filtered']) {
  const pageDirectory = path.join(source, 'ui', page);
  for (const file of await readdir(pageDirectory)) {
    await copy(path.join(pageDirectory, file), path.join(output, file));
  }
}

for (const size of ['16', '48', '128']) {
  await copy(path.join(root, 'assets', 'icons', `${size}.png`), path.join(output, 'icons', `${size}.png`));
}
await copy(path.join(root, 'assets', 'sprites'), path.join(output, 'sprites'));
await copy(path.join(root, 'assets', 'flags'), path.join(output, 'flags'));
await copy(path.join(root, 'assets', 'world-map.svg'), path.join(output, 'world-map.svg'));

console.log(`Built Feedpecker in ${path.relative(root, output)}/`);
